/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 200 when the audit store opens read-only and answers a query.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Meta
         * @description App/env info, cadences with stale thresholds, gate caps and client defaults.
         */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Snapshot
         * @description Every dashboard section read in one pass (SELECT only), with the gate's caps.
         */
        get: operations["snapshot_api_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppInfo */
        AppInfo: {
            /** Git Sha */
            git_sha?: string | null;
            /**
             * Name
             * @default arc
             * @constant
             */
            name: "arc";
            /** Version */
            version: string;
        };
        /**
         * Cadence
         * @description How often a producing job runs and when its output counts as stale.
         */
        Cadence: {
            /**
             * Days
             * @description daily | trading | weekdays | mon,fri…
             */
            days?: string | null;
            /**
             * Every S
             * @description Nominal seconds between runs
             */
            every_s: number;
            /** Job */
            job: string;
            /**
             * Label
             * @description Human cadence, e.g. 'every 30m 09:30-16:00 ET (trading)'
             */
            label: string;
            /**
             * Stale After S
             * @description 3 x every_s
             */
            stale_after_s: number;
            /**
             * Window
             * @description Intraday window (ET), if any
             */
            window?: string | null;
        };
        /**
         * ErrorResponse
         * @description Every non-2xx response: ``{error, detail, as_of}``.
         */
        ErrorResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /**
             * Detail
             * @description Human-readable explanation
             */
            detail: string;
            /**
             * Error
             * @description Stable machine code, e.g. db_unavailable, not_found
             */
            error: string;
        };
        /**
         * GateCaps
         * @description The gate's portfolio caps (PLAN §5), from the effective settings.
         */
        GateCaps: {
            /**
             * Portfolio Delta Cap
             * @description |net Δ| cap: × equity/100, share-eq
             */
            portfolio_delta_cap: number;
            /**
             * Portfolio Vega Cap Pct
             * @description |ν| cap as a fraction of equity
             */
            portfolio_vega_cap_pct: number;
        };
        /** GateViolation */
        GateViolation: {
            /** Code */
            code: string;
            /** Decided At */
            decided_at: string | null;
            /** Detail */
            detail: string;
            /** Kind */
            kind: string;
            /** Proposal Hash */
            proposal_hash: string;
            /** Ticker */
            ticker: string | null;
        };
        /**
         * GreeksView
         * @description Net portfolio Greeks from the latest monitor run (share-equivalents, as the gate).
         */
        GreeksView: {
            /** At */
            at?: string | null;
            /** Delta */
            delta?: number | null;
            /**
             * Delta Cap
             * @description |Δ| cap, share-eq (cap × equity/100)
             */
            delta_cap?: number | null;
            /** Equity */
            equity?: number | null;
            /** Gamma */
            gamma?: number | null;
            /** Max Loss */
            max_loss?: number | null;
            /** Positions */
            positions?: number | null;
            /** Theta */
            theta?: number | null;
            /**
             * Valued
             * @default false
             */
            valued: boolean;
            /** Vega */
            vega?: number | null;
            /**
             * Vega Cap Usd
             * @description |ν| cap, $ per vol point
             */
            vega_cap_usd?: number | null;
            /**
             * Vega Usd
             * @description ν in $ per vol point (ν/100)
             */
            vega_usd?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HaltView */
        HaltView: {
            /** Active */
            active: boolean;
            /** Actor */
            actor: string;
            /** At */
            at: string | null;
            /** Cleared At */
            cleared_at: string | null;
            /** Cleared By */
            cleared_by: string | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Reason */
            reason: string;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /**
             * Db
             * @description Audit store path, opened read-only
             */
            db: string;
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** LegView */
        LegView: {
            /**
             * Asset Class
             * @default us_option
             */
            asset_class: string;
            /** Avg Entry Price */
            avg_entry_price?: string | null;
            /** Market Value */
            market_value?: string | null;
            /** Qty */
            qty: string;
            /** Side */
            side: string;
            /** Symbol */
            symbol: string;
            /** Unrealized Pl */
            unrealized_pl?: string | null;
        };
        /** MetaResponse */
        MetaResponse: {
            /** Account Profile */
            account_profile: string;
            app: components["schemas"]["AppInfo"];
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /**
             * Cadences
             * @description monitor, auditor, tick
             */
            cadences: {
                [key: string]: components["schemas"]["Cadence"];
            };
            /**
             * Config Version
             * @description Latest D26 config_changes id (0 = none)
             */
            config_version: number;
            /**
             * Env
             * @description ARC_ENV (paper | live)
             */
            env: string;
            gate_caps: components["schemas"]["GateCaps"];
            /** Lookback Days */
            lookback_days: number;
            /** Refresh Choices S */
            refresh_choices_s?: number[];
            /**
             * Refresh Interval S
             * @description Default client poll interval
             */
            refresh_interval_s: number;
            /**
             * Theme Default
             * @default system
             * @enum {string}
             */
            theme_default: "system" | "light" | "dark";
        };
        /** OpsView */
        OpsView: {
            /** Health At */
            health_at?: string | null;
            /** Health Status */
            health_status?: string | null;
            /** Open Alerts */
            open_alerts?: {
                [key: string]: string;
            }[];
            /** Tick At */
            tick_at?: string | null;
            /** Tick Status */
            tick_status?: string | null;
        };
        /**
         * Performance
         * @description Account Day/MTD/YTD performance from ``pnl_snapshots`` (E6.3, D28). $ and fractions.
         *
         *     Shared by the Auditor digest (:mod:`arc.slack.digests`) and the control tower.
         */
        Performance: {
            /** Day Pct */
            day_pct?: number | null;
            /** Day Pnl */
            day_pnl: number;
            /** Equity */
            equity?: number | null;
            /** Mtd Pct */
            mtd_pct?: number | null;
            /** Mtd Pnl */
            mtd_pnl?: number | null;
            /** Ytd Pct */
            ytd_pct?: number | null;
            /** Ytd Pnl */
            ytd_pnl?: number | null;
        };
        /**
         * PnlView
         * @description Account P&L: the last reconciled snapshot plus the latest intraday mark.
         */
        PnlView: {
            /** Day Pnl */
            day_pnl?: string | null;
            /** Equity */
            equity?: string | null;
            /** Equity Series */
            equity_series?: [
                string,
                string
            ][];
            /** Intraday At */
            intraday_at?: string | null;
            /** Intraday Day Pnl */
            intraday_day_pnl?: string | null;
            /** Intraday Equity */
            intraday_equity?: string | null;
            performance?: components["schemas"]["Performance"] | null;
            /** Realized */
            realized?: string | null;
            /** Reconcile Clean */
            reconcile_clean?: boolean | null;
            /** Reconciled At */
            reconciled_at?: string | null;
            /** Reconciled Day */
            reconciled_day?: string | null;
            /** Total */
            total?: string | null;
            /** Unrealized */
            unrealized?: string | null;
        };
        /** ProposalView */
        ProposalView: {
            /** Approval */
            approval?: string | null;
            /** Contracts */
            contracts: number | null;
            /** Created At */
            created_at: string | null;
            /** Day */
            day: string | null;
            /** Ev */
            ev: string | null;
            /** Execution */
            execution?: string | null;
            /** Fill Price */
            fill_price?: string | null;
            /** Gate Passed */
            gate_passed: boolean | null;
            /** Kind */
            kind: string;
            /** Limit */
            limit: string | null;
            /** Pop */
            pop: number | null;
            /** Proposal Hash */
            proposal_hash: string;
            /** Structure Kind */
            structure_kind: string | null;
            /** Ticker */
            ticker: string | null;
            /** Violations */
            violations?: string[];
        };
        /** StructureView */
        StructureView: {
            /** Contracts */
            contracts: number;
            /** Entry Net */
            entry_net: string;
            /**
             * Exit Pending
             * @default false
             */
            exit_pending: boolean;
            /** Exit Reason */
            exit_reason?: string | null;
            /** Expiration */
            expiration: string | null;
            /**
             * Held
             * @description Last reconcile found it at the broker
             */
            held?: boolean | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string | null;
            /** Opened At */
            opened_at: string | null;
            /** Status */
            status: string;
            /** Ticker */
            ticker: string;
            /**
             * Unrealized Pl
             * @description Sum over its legs' broker P&L
             */
            unrealized_pl?: string | null;
        };
        /**
         * TowerSnapshot
         * @description Everything the dashboard shows, read in one pass.
         */
        TowerSnapshot: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Db Path */
            db_path: string;
            greeks: components["schemas"]["GreeksView"];
            /** Halts */
            halts: components["schemas"]["HaltView"][];
            /** Legs */
            legs: components["schemas"]["LegView"][];
            ops: components["schemas"]["OpsView"];
            pnl: components["schemas"]["PnlView"];
            /** Proposals */
            proposals: components["schemas"]["ProposalView"][];
            /** Structures */
            structures: components["schemas"]["StructureView"][];
            /** Violation Counts */
            violation_counts: {
                [key: string]: number;
            };
            /** Violations */
            violations: components["schemas"]["GateViolation"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    snapshot_api_snapshot_get: {
        parameters: {
            query?: {
                lookback_days?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TowerSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
