/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 200 when the audit store opens read-only and answers a query.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Meta
         * @description App/env info, cadences with stale thresholds, gate caps and client defaults.
         */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Overview
         * @description Status strip, equity (by range), day P&L, positions, Greeks vs caps, proposals,
         *     movers and recent activity, read in one pass (SELECT only).
         */
        get: operations["overview_api_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Positions
         * @description Open, closed or all structures with the latest broker marks.
         */
        get: operations["positions_api_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Snapshot
         * @description Every dashboard section read in one pass (SELECT only), with the gate's caps.
         */
        get: operations["snapshot_api_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityItem */
        ActivityItem: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "fill" | "execution" | "exit" | "halt" | "resume" | "reconcile" | "alert";
            /**
             * Ref
             * @description proposal hash for a drill-down link
             */
            ref?: string | null;
            /** Text */
            text: string;
            /**
             * Tone
             * @default neutral
             * @enum {string}
             */
            tone: "neutral" | "neg" | "warn" | "pos";
        };
        /** AlertView */
        AlertView: {
            /** Key */
            key: string;
            /** Kind */
            kind: string;
            /** Message */
            message: string;
            /** Opened At */
            opened_at: string | null;
        };
        /** AppInfo */
        AppInfo: {
            /** Git Sha */
            git_sha?: string | null;
            /**
             * Name
             * @default arc
             * @constant
             */
            name: "arc";
            /** Version */
            version: string;
        };
        /**
         * Cadence
         * @description How often a producing job runs and when its output counts as stale.
         */
        Cadence: {
            /**
             * Days
             * @description daily | trading | weekdays | mon,fri…
             */
            days?: string | null;
            /**
             * Every S
             * @description Nominal seconds between runs
             */
            every_s: number;
            /** Job */
            job: string;
            /**
             * Label
             * @description Human cadence, e.g. 'every 30m 09:30-16:00 ET (trading)'
             */
            label: string;
            /**
             * Stale After S
             * @description 3 x every_s
             */
            stale_after_s: number;
            /**
             * Window
             * @description Intraday window (ET), if any
             */
            window?: string | null;
        };
        /**
         * DayPnlSection
         * @description Day P&L (equity − broker's prior close), realized vs unrealized, MTD / YTD.
         */
        DayPnlSection: {
            /** As Of */
            as_of?: string | null;
            /** Day Pct */
            day_pct?: number | null;
            /** Day Pnl */
            day_pnl?: string | null;
            performance?: components["schemas"]["Performance"] | null;
            /**
             * Performance Day
             * @description Day MTD/YTD refer to
             */
            performance_day?: string | null;
            /** Prev Equity */
            prev_equity?: string | null;
            /**
             * Realized
             * @description Realized today (reconciled)
             */
            realized?: string | null;
            /** Realized At */
            realized_at?: string | null;
            /** Source */
            source?: ("intraday" | "reconciled") | null;
            /**
             * Unrealized
             * @description Open legs' broker P&L
             */
            unrealized?: string | null;
            /** Unrealized At */
            unrealized_at?: string | null;
        };
        /** EquityPoint */
        EquityPoint: {
            /**
             * T
             * Format: date-time
             */
            t: string;
            /** V */
            v: string;
        };
        /**
         * EquitySection
         * @description Hero equity, its change over the selected range and the series to plot.
         */
        EquitySection: {
            /** Change */
            change?: string | null;
            /**
             * Change Pct
             * @description change / start_value (fraction)
             */
            change_pct?: number | null;
            /**
             * Range
             * @enum {string}
             */
            range: "1D" | "1W" | "1M" | "3M" | "YTD" | "ALL";
            /** Series */
            series?: components["schemas"]["EquityPoint"][];
            /**
             * Series Source
             * @default daily
             * @enum {string}
             */
            series_source: "intraday" | "daily";
            /**
             * Source
             * @description intraday = latest monitor mark; reconciled = pnl_snapshots
             */
            source?: ("intraday" | "reconciled") | null;
            /** Start At */
            start_at?: string | null;
            /**
             * Start Label
             * @description 'prev close' or the start day
             */
            start_label?: string | null;
            /**
             * Start Value
             * @description Equity at the range start
             */
            start_value?: string | null;
            /** Value */
            value?: string | null;
            /** Value At */
            value_at?: string | null;
        };
        /**
         * ErrorResponse
         * @description Every non-2xx response: ``{error, detail, as_of}``.
         */
        ErrorResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /**
             * Detail
             * @description Human-readable explanation
             */
            detail: string;
            /**
             * Error
             * @description Stable machine code, e.g. db_unavailable, not_found
             */
            error: string;
        };
        /**
         * GateCaps
         * @description The gate's portfolio caps (PLAN §5), from the effective settings.
         */
        GateCaps: {
            /**
             * Portfolio Delta Cap
             * @description |net Δ| cap: × equity/100, share-eq
             */
            portfolio_delta_cap: number;
            /**
             * Portfolio Vega Cap Pct
             * @description |ν| cap as a fraction of equity
             */
            portfolio_vega_cap_pct: number;
        };
        /** GateViolation */
        GateViolation: {
            /** Code */
            code: string;
            /** Decided At */
            decided_at: string | null;
            /** Detail */
            detail: string;
            /** Kind */
            kind: string;
            /** Proposal Hash */
            proposal_hash: string;
            /** Ticker */
            ticker: string | null;
        };
        /** GreeksSection */
        GreeksSection: {
            greeks: components["schemas"]["GreeksView"];
            /** Max Alloc Pct */
            max_alloc_pct: number;
            /** Max Loss By Underlying */
            max_loss_by_underlying?: {
                [key: string]: string;
            };
            /**
             * Per Underlying Cap
             * @description max_alloc_pct × equity (gate rule)
             */
            per_underlying_cap?: string | null;
        };
        /**
         * GreeksView
         * @description Net portfolio Greeks from the latest monitor run (share-equivalents, as the gate).
         */
        GreeksView: {
            /** At */
            at?: string | null;
            /** Delta */
            delta?: number | null;
            /**
             * Delta Cap
             * @description |Δ| cap, share-eq (cap × equity/100)
             */
            delta_cap?: number | null;
            /** Equity */
            equity?: number | null;
            /** Gamma */
            gamma?: number | null;
            /** Max Loss */
            max_loss?: number | null;
            /** Positions */
            positions?: number | null;
            /**
             * Stale After S
             * @description Monitor marks older than this are stale: 3x the monitor cadence (E5.3a)
             * @default 900
             */
            stale_after_s: number;
            /** Theta */
            theta?: number | null;
            /**
             * Valued
             * @default false
             */
            valued: boolean;
            /** Vega */
            vega?: number | null;
            /**
             * Vega Cap Usd
             * @description |ν| cap, $ per vol point
             */
            vega_cap_usd?: number | null;
            /**
             * Vega Usd
             * @description ν in $ per vol point (ν/100)
             */
            vega_usd?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HaltView */
        HaltView: {
            /** Active */
            active: boolean;
            /** Actor */
            actor: string;
            /** At */
            at: string | null;
            /** Cleared At */
            cleared_at: string | null;
            /** Cleared By */
            cleared_by: string | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Reason */
            reason: string;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /**
             * Db
             * @description Audit store path, opened read-only
             */
            db: string;
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** LegView */
        LegView: {
            /**
             * Asset Class
             * @default us_option
             */
            asset_class: string;
            /** Avg Entry Price */
            avg_entry_price?: string | null;
            /** Change Today */
            change_today?: string | null;
            /** Current Price */
            current_price?: string | null;
            /** Lastday Price */
            lastday_price?: string | null;
            /** Market Value */
            market_value?: string | null;
            /** Qty */
            qty: string;
            /** Side */
            side: string;
            /** Symbol */
            symbol: string;
            /** Unrealized Pl */
            unrealized_pl?: string | null;
        };
        /** MetaResponse */
        MetaResponse: {
            /** Account Profile */
            account_profile: string;
            app: components["schemas"]["AppInfo"];
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /**
             * Cadences
             * @description monitor, auditor, tick
             */
            cadences: {
                [key: string]: components["schemas"]["Cadence"];
            };
            /**
             * Config Version
             * @description Latest D26 config_changes id (0 = none)
             */
            config_version: number;
            /**
             * Env
             * @description ARC_ENV (paper | live)
             */
            env: string;
            gate_caps: components["schemas"]["GateCaps"];
            /** Lookback Days */
            lookback_days: number;
            /** Refresh Choices S */
            refresh_choices_s?: number[];
            /**
             * Refresh Interval S
             * @description Default client poll interval
             */
            refresh_interval_s: number;
            /**
             * Theme Default
             * @default system
             * @enum {string}
             */
            theme_default: "system" | "light" | "dark";
        };
        /** MoverTile */
        MoverTile: {
            /** At */
            at?: string | null;
            /**
             * Change Today
             * @description Structure day change: legs' change_today weighted by value
             */
            change_today?: number | null;
            /** Kind */
            kind: string | null;
            /** Open Proposal Hash */
            open_proposal_hash: string;
            /**
             * Spark
             * @description Unrealized $ over today's marks
             */
            spark?: number[];
            /** Structure Id */
            structure_id: string;
            /** Ticker */
            ticker: string;
            /** Unrealized Pct */
            unrealized_pct?: number | null;
        };
        /** OpsView */
        OpsView: {
            /** Health At */
            health_at?: string | null;
            /** Health Status */
            health_status?: string | null;
            /** Open Alerts */
            open_alerts?: {
                [key: string]: string;
            }[];
            order_budget?: components["schemas"]["OrderBudgetView"] | null;
            /** Tick At */
            tick_at?: string | null;
            /** Tick Status */
            tick_status?: string | null;
        };
        /**
         * OrderBudgetView
         * @description D32 daily order budget as the last monitor heartbeat saw it.
         */
        OrderBudgetView: {
            /** As Of */
            as_of?: string | null;
            /** Limit */
            limit: number;
            /** Tier */
            tier: string;
            /** Used */
            used: number;
        };
        /**
         * OverviewResponse
         * @description ``GET /api/overview``: every Overview card in one read.
         */
        OverviewResponse: {
            /** Activity */
            activity: components["schemas"]["ActivityItem"][];
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            day_pnl: components["schemas"]["DayPnlSection"];
            equity: components["schemas"]["EquitySection"];
            greeks: components["schemas"]["GreeksSection"];
            /**
             * Marks At
             * @description Latest monitor heartbeat
             */
            marks_at?: string | null;
            /**
             * Marks Stale
             * @description No monitor mark, or older than stale_after_s at as_of
             */
            marks_stale: boolean;
            /** Movers */
            movers: components["schemas"]["MoverTile"][];
            /** Positions */
            positions: components["schemas"]["PositionRow"][];
            /** Proposals */
            proposals: components["schemas"]["ProposalRow"][];
            /**
             * Proposals Since
             * Format: date-time
             */
            proposals_since: string;
            /**
             * Range
             * @enum {string}
             */
            range: "1D" | "1W" | "1M" | "3M" | "YTD" | "ALL";
            /**
             * Stale After S
             * @description Monitor marks older than this are stale
             */
            stale_after_s: number;
            status: components["schemas"]["StatusSection"];
        };
        /**
         * Performance
         * @description Account Day/MTD/YTD performance from ``pnl_snapshots`` (E6.3, D28). $ and fractions.
         *
         *     Shared by the Auditor digest (:mod:`arc.slack.digests`) and the control tower.
         */
        Performance: {
            /** Day Pct */
            day_pct?: number | null;
            /** Day Pnl */
            day_pnl: number;
            /** Equity */
            equity?: number | null;
            /** Mtd Pct */
            mtd_pct?: number | null;
            /** Mtd Pnl */
            mtd_pnl?: number | null;
            /** Ytd Pct */
            ytd_pct?: number | null;
            /** Ytd Pnl */
            ytd_pnl?: number | null;
        };
        /**
         * PnlView
         * @description Account P&L: the last reconciled snapshot plus the latest intraday mark.
         */
        PnlView: {
            /** Day Pnl */
            day_pnl?: string | null;
            /** Equity */
            equity?: string | null;
            /** Equity Series */
            equity_series?: [
                string,
                string
            ][];
            /** Intraday At */
            intraday_at?: string | null;
            /** Intraday Day Pnl */
            intraday_day_pnl?: string | null;
            /** Intraday Equity */
            intraday_equity?: string | null;
            performance?: components["schemas"]["Performance"] | null;
            /** Realized */
            realized?: string | null;
            /** Reconcile Clean */
            reconcile_clean?: boolean | null;
            /** Reconciled At */
            reconciled_at?: string | null;
            /** Reconciled Day */
            reconciled_day?: string | null;
            /** Total */
            total?: string | null;
            /** Unrealized */
            unrealized?: string | null;
        };
        /**
         * PositionRow
         * @description One structure: entry vs mark per share (+ debit / − credit), P&L from its legs.
         */
        PositionRow: {
            /** Close Net */
            close_net?: string | null;
            /** Closed At */
            closed_at?: string | null;
            /** Contracts */
            contracts: number;
            /**
             * Day Change
             * @description $ change today (broker marks)
             */
            day_change?: string | null;
            /** Dte */
            dte?: number | null;
            /** Entry Net */
            entry_net: string;
            /**
             * Exit Pending
             * @default false
             */
            exit_pending: boolean;
            /** Exit Proposal Hash */
            exit_proposal_hash?: string | null;
            /** Exit Reason */
            exit_reason?: string | null;
            /** Expiration */
            expiration?: string | null;
            /**
             * Held
             * @description Last reconcile found it at the broker
             */
            held?: boolean | null;
            /** Held At */
            held_at?: string | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string | null;
            /**
             * Legs
             * @description Compact OCC symbols
             */
            legs: string[];
            /** Mark At */
            mark_at?: string | null;
            /**
             * Mark Net
             * @description Σ legs' broker mark, per share
             */
            mark_net?: string | null;
            /**
             * Max Loss
             * @description Structure max loss × contracts
             */
            max_loss?: string | null;
            /** Open Proposal Hash */
            open_proposal_hash: string;
            /** Opened At */
            opened_at?: string | null;
            /**
             * Realized Pl
             * @description Closed: −(entry+close)×100×n
             */
            realized_pl?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "closed";
            /** Ticker */
            ticker: string;
            /**
             * Unrealized Pct
             * @description P&L / |entry| × 100 × n
             */
            unrealized_pct?: number | null;
            /** Unrealized Pl */
            unrealized_pl?: string | null;
        };
        /**
         * PositionsResponse
         * @description ``GET /api/positions``: open and/or closed structures.
         */
        PositionsResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Items */
            items: components["schemas"]["PositionRow"][];
            /** Marks At */
            marks_at?: string | null;
            /** Stale After S */
            stale_after_s: number;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "closed" | "all";
        };
        /**
         * ProposalRow
         * @description A proposal with its net EV after costs (E2.4 managed model × contracts).
         */
        ProposalRow: {
            /** Approval */
            approval?: string | null;
            /** Contracts */
            contracts: number | null;
            /** Created At */
            created_at: string | null;
            /** Day */
            day: string | null;
            /** Ev */
            ev: string | null;
            /** Execution */
            execution?: string | null;
            /** Fill Price */
            fill_price?: string | null;
            /** Gate Passed */
            gate_passed: boolean | null;
            /** Kind */
            kind: string;
            /** Limit */
            limit: string | null;
            /**
             * Net Ev
             * @description Managed net EV × contracts, $
             */
            net_ev?: number | null;
            /** Pop */
            pop: number | null;
            /** Pop Managed */
            pop_managed?: number | null;
            /** Proposal Hash */
            proposal_hash: string;
            /** Structure Kind */
            structure_kind: string | null;
            /** Ticker */
            ticker: string | null;
            /** Violations */
            violations?: string[];
        };
        /** ProposalView */
        ProposalView: {
            /** Approval */
            approval?: string | null;
            /** Contracts */
            contracts: number | null;
            /** Created At */
            created_at: string | null;
            /** Day */
            day: string | null;
            /** Ev */
            ev: string | null;
            /** Execution */
            execution?: string | null;
            /** Fill Price */
            fill_price?: string | null;
            /** Gate Passed */
            gate_passed: boolean | null;
            /** Kind */
            kind: string;
            /** Limit */
            limit: string | null;
            /** Pop */
            pop: number | null;
            /** Proposal Hash */
            proposal_hash: string;
            /** Structure Kind */
            structure_kind: string | null;
            /** Ticker */
            ticker: string | null;
            /** Violations */
            violations?: string[];
        };
        /**
         * StatusSection
         * @description Full-width strip: trading state, scheduler health, alerts, D32 budget.
         */
        StatusSection: {
            /**
             * Active Halts
             * @default 0
             */
            active_halts: number;
            /** Alerts */
            alerts?: components["schemas"]["AlertView"][];
            /** @description Most recent active halt */
            halt?: components["schemas"]["HaltView"] | null;
            /** Halted */
            halted: boolean;
            /** Health At */
            health_at?: string | null;
            /** Health Status */
            health_status?: string | null;
            /** @description Absent until the monitor heartbeat carries it (E6.5) */
            order_budget?: components["schemas"]["OrderBudgetView"] | null;
            /** Tick At */
            tick_at?: string | null;
            /** Tick Status */
            tick_status?: string | null;
        };
        /** StructureView */
        StructureView: {
            /** Contracts */
            contracts: number;
            /** Entry Net */
            entry_net: string;
            /**
             * Exit Pending
             * @default false
             */
            exit_pending: boolean;
            /** Exit Reason */
            exit_reason?: string | null;
            /** Expiration */
            expiration: string | null;
            /**
             * Held
             * @description Last reconcile found it at the broker
             */
            held?: boolean | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string | null;
            /** Opened At */
            opened_at: string | null;
            /** Status */
            status: string;
            /** Ticker */
            ticker: string;
            /**
             * Unrealized Pl
             * @description Sum over its legs' broker P&L
             */
            unrealized_pl?: string | null;
        };
        /**
         * TowerSnapshot
         * @description Everything the dashboard shows, read in one pass.
         */
        TowerSnapshot: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Db Path */
            db_path: string;
            greeks: components["schemas"]["GreeksView"];
            /** Halts */
            halts: components["schemas"]["HaltView"][];
            /** Legs */
            legs: components["schemas"]["LegView"][];
            ops: components["schemas"]["OpsView"];
            pnl: components["schemas"]["PnlView"];
            /** Proposals */
            proposals: components["schemas"]["ProposalView"][];
            /** Structures */
            structures: components["schemas"]["StructureView"][];
            /** Violation Counts */
            violation_counts: {
                [key: string]: number;
            };
            /** Violations */
            violations: components["schemas"]["GateViolation"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    overview_api_overview_get: {
        parameters: {
            query?: {
                range?: "1D" | "1W" | "1M" | "3M" | "YTD" | "ALL";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    positions_api_positions_get: {
        parameters: {
            query?: {
                status?: "open" | "closed" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    snapshot_api_snapshot_get: {
        parameters: {
            query?: {
                lookback_days?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TowerSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
